### ISSUE TITLE
Displaying bitmap

### ISSUE THREAD

**Issue by diasrobson** [daschr/pico-ssd1306#2]
Hi there amazing work on this library. I was just wondering dose it support displaying custom bit arrays to display images

**Comment by daschr** [comment]
Thank you! I'm sorry for the late reply. I'll add this feature until weekend.

**Comment by daschr** [comment]
I've added support for monochrome bitmaps. See the example and https://daschr.github.io/pico-ssd1306/ssd1306_8h.html#a89d1f4edb34d5860df01a62512cc3949
