### ISSUE TITLE
Character spacing uses height rather than width

### ISSUE THREAD

**Issue by beeka** [daschr/pico-ssd1306#3]
When drawing a string with the `ssd1306_draw_string_with_font()` function the 'stride' is taken from [font[0]](https://github.com/daschr/pico-ssd1306/blob/52ff83c4a9cc863dbb8fdc87df86447f8e20d61e/ssd1306.c#L200), i.e. `x_n+=font[0]*scale`, which is the character height rather than the width. The 'fix' should be to use `font[1]` but the 8x5 font doesn't have any whitespace in the glyphs so they butt against each other (nice and compact though). A font spacing constant of one pixel can be used, e.g. `x_n+=font[1]*scale+1` to work-around this. This is still two pixels per char closer together. If the current spacing was intentional it would be clearer / more reliable if it was explicit, e.g. `x_n+=font[1]*scale+3`

BTW: I found this while converting an 8x8 bitmap font, however this had the spacing built-in (i.e. designed to be laid next to each other) so looked quite spaced out...  and a 16x8 font more so (once I had updated `ssd1306_draw_char_with_font()` to handle larger chars). I am inclined to add a 'tracking' parameter to the front of the font array. The character set I am converting has the full 256 entries, so I am also inclined to add 'first char' and 'glyph count' parameters to the font array. I'd follow a standard, if I could find one :-)

**Comment by nickandre** [comment]
heh you made this exact change too :)

**Comment by daschr** [comment]
Hi!

Sorry for the very late reply :/

I've added some parameters to the font data which enables fonts bigger heights, more characters and adjustable spacing (see the Readme.md and example).
Would be great if you can try it out with your font.

Cheers,

David

**Comment by daschr** [comment]
I'm closing this issue since it does not seem to be relevant anymore. Feel free to reopen it.
