### ISSUE TITLE
Conversion from BMP to image.h format

### ISSUE THREAD

**Issue by mytechnotalent** [daschr/pico-ssd1306#5]
What tool did you use to convert the BMP image to image.h format?  What would be the steps to convert ones own image?  In addition does your image function allow for only a partial image to be painted or must it be the entire screen?  It would be nice to allow say a 20x20 image to be painted at x=25, y=30 for example.

**Comment by daschr** [comment]
bin2c, I've added a description in the [README](https://github.com/daschr/pico-ssd1306#draw-images).
You can use the [*ssd1306_bmp_show_image_with_offset*](https://daschr.github.io/pico-ssd1306/ssd1306_8h.html#a1624a5ea20392d5614b84094e94160b0) function for displaying an image with an offset.
Displaying only a part of an image or clipping it is currently not supported. If this is needed, I would add support for it.
Feel free to reopen the issue if something is unclear.

Cheers,

David
