### ISSUE TITLE
Display shows static

### ISSUE THREAD

**Issue by stigl-cc** [daschr/pico-ssd1306#8]
Sometimes when i init display, clear it and want to print something, there is just static
Any solution?

**Comment by daschr** [comment]
So you mean that it is not showing the newly drawn content after you called `ssd1306_show`?

Can you provide me the part of your code where this happens?
I'll try to reproduce it and see if I get the same behavior.

It can also be a loosy connection between the pico and the display, You may check this by wiggling the connectors on both ends of your cables while you are continuously drawing something which is changing (for example the [example](https://github.com/daschr/pico-ssd1306/tree/main/example)).

**Comment by stigl-cc** [comment]
Its propably not cable error, because example works everytime fine.

**Comment by stigl-cc** [comment]
Ill try to make replication.

**Comment by stigl-cc** [comment]
It seems like issue is no longer there!
